### ISSUE TITLE
[FEATURE] Show warning if you are about to deploy different than current instance branch

### ISSUE THREAD

**Issue by benjaminrau** [sourcebroker/deployer-extended#6]
If you run a deployment, Deployer is checking the deploy.php file in the branch you currently checked out in local GIT. Other branches could have other definition for set branch, which is used for the instance to be deployed.

One could mistakenly deploy a branch which should not be used for this instance currently, because of this. Especially if the one who is about to deploy doesnt know about this (temporary) different branch which is used currently on target instance / machine, he wouldnt doubt to deploy from the branch he was used to use for the target instance.

My suggestion is that on deployment a new task checks which branch is checked out on target server (instance to be deployed to) right now and if it doesnt match the branch which is about to be deployed, give interactive feedback if this is a desired action.

Smth like: "Attention, you are going to deploy branch XY while on the target instance currently branch Z is active. You want to continue?"

**Comment by kszymukowicz** [comment]
Yes. That can be nice task. 
I will take care of that as soon as I will get some time.

**Comment by kszymukowicz** [comment]
It took some time but finally this functionality is there. 
You can have two tasks now that should do what you want:
https://github.com/sourcebroker/deployer-extended#deploy-check-branch
https://github.com/sourcebroker/deployer-extended#deploy-check-branch-local

**Comment by benjaminrau** [comment]
Great news! I will give it a try :) Thanks!
