### ISSUE TITLE
deploy:check_branch_local fails on Windows

### ISSUE THREAD

**Issue by indrek-k** [sourcebroker/deployer-extended#9]
Getting the following error in git bash as well as other consoles.

```
  [Symfony\Component\Process\Exception\ProcessFailedException]
  The command "if [ -d .git ]; then echo 'true'; fi" failed.

  Exit Code: 1(General error)

  Working directory: C:\Laragon\www\deploytest

  Output:
  ================


  Error Output:
  ================

```

However, running the exact same command in a simple shell script works properly.

Any idea what might cause this?

Thanks!

**Comment by kszymukowicz** [comment]
No idea. I do not test that on Windows at all.

**Comment by kszymukowicz** [comment]
BTW: If you use windows then plz try WSL2/Ubuntu. You can have real Linux on Windows - no more problems.
